# Generated by Django 4.0.6 on 2022-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterschedulermodel',
            name='otp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
