# Generated by Django 4.0.6 on 2022-07-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0003_twitterschedulermodel_resource_owner_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterschedulermodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
